{% set name = "hepunits" %}
{% set version = "2.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hepunits-{{ version }}.tar.gz
  sha256: 67d7cc77cd54d72b69c26a68e5efad7842b6f68fa8bc627bb90e41177abe6945

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - hatchling
    - hatch-vcs
    - toml
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4

test:
  imports:
    - hepunits
    - hepunits.constants
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/hepunits
  summary: Units and constants in the HEP system of units
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
    - chrisburr
