{% set name = "hepunits" %}
{% set version = "2.3.5" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hepunits-{{ version }}.tar.gz
  sha256: 9434cd2d6a722c949e9e9e22bd0b59587f69025bd37356e5c70635f1b37036d8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - toml
  run:
    - python >={{ python_min }}

test:
  imports:
    - hepunits
    - hepunits.constants
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scikit-hep/hepunits
  summary: Units and constants in the HEP system of units
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scikit-hep/hepunits

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
    - chrisburr
