{% set name = "hepunits" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hepunits-{{ version }}.tar.gz
  sha256: e80e616fef2817f3c66c75dc0e41ed26362488cce05f94adcfdefb8e05ebcb58

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - setuptools_scm
    - toml
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4

test:
  imports:
    - hepunits
    - hepunits.constants
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/hepunits
  summary: Units and constants in the HEP system of units
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
