schema_version: 1

context:
  name: hepunits
  version: "2.4.1"
  python_min: '3.8'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/hepunits-${{ version }}.tar.gz
  sha256: 141ef23efedc5bb05c03411a3584cbfd3c7e76a1f378498cba4401dda82f69fc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - toml
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - hepunits
        - hepunits.constants
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Units and constants in the HEP system of units
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/hepunits
  repository: https://github.com/scikit-hep/hepunits

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
    - chrisburr
